REGION_FLAGS = {
  "United Kingdom": 'GB'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Illinois": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "California (North)": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Florida": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Colorado": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Pennsylvania": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Virginia": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Georgia": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "California (South)": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Chile": 'CL'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Washington": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Wisconsin": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Ohio": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Quebec": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Unspecified": "🏳",
  "Nebraska": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Colombia": 'CO'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Arkansas": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New York": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Japan": 'JP'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Tennessee": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Texas": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Massachusetts": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New Zealand": 'CK'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New Mexico": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Michigan": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Sweden": 'SE'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Maryland": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "North Carolina": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Poland": 'PL'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Finland": 'FI'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New Jersey": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Utah": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Ontario": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Minnesota": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Arizona": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Louisiana": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Puerto Rico": 'PR'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Philippines": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Connecticut": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Alabama": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Hawaii": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Italy": 'IT'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Idaho": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Indiana": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Mexico": 'MX'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Oregon": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Missouri": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Nevada": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "France": 'FR'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Manitoba": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Brazil": 'BR'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Delaware": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Oklahoma": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Iowa": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Maine": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Netherlands": 'NL'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Peru": 'PE'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Australia": 'AU'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Uruguay": 'UY'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Germany": 'DE'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "South Carolina": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Kentucky": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New Hampshire": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Switzerland": 'CH'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Rhode Island": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Venezuela": 'VE'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Alberta": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "West Virginia": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Czech Republic": 'CZ'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "British Columbia": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "South Korea": 'KR'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "New Brunswick": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Austria": 'AT'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Mississippi": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Russian Federation": 'RU'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Spain": 'ES'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Scotland": 'GB'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Kansas": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Denmark": 'DK'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
  "Alaska": 'US'.tr('A-Z', "\u{1F1E6}-\u{1F1FF}"),
}

EU_REGIONS = ["Austria", "Czech Republic", "Denmark", "Finland", "France", "Germany", "Italy", "Netherlands", "Poland", "Russian Federation", "Scotland", "Spain", "Sweden", "Switzerland", "United Kingdom"]
PL_REGIONS = ["Poland"]
US_REGIONS = ["Alabama", "Alaska", "Alberta", "Arizona", "Arkansas", "British Columbia",
  "California (North)", "California (South)", "Colorado", "Connecticut",
  "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana",
  "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Manitoba", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
  "Nebraska", "Nevada", "New Brunswick", "New Hampshire", "New Jersey",
  "New Mexico", "New York", "North Carolina", "Ohio", "Oklahoma", "Ontario",
  "Oregon", "Pennsylvania", "Philippines", "Quebec", "Rhode Island",
  "South Carolina", "Tennessee", "Texas", "Utah", "Virginia", "Washington",
  "West Virginia", "Wisconsin"
]

REGIONS_LIST = {
  "eu": EU_REGIONS,
  "pl": PL_REGIONS,
  "us": US_REGIONS,
  "world": REGION_FLAGS.keys
}